---
pid: /var/www/allods/prod/current/tmp/pids/thin.pid
address: 0.0.0.0
timeout: 5
port: 5000
log: /var/www/allods/prod/current/log/thin.log
max_conns: 1024
require: ['rubygems']

environment: production
max_persistent_conns: 512
servers: 1
daemonize: true
chdir: /var/www/allods/prod/current
