---
pid: /home/jd/allods/webapp/current/tmp/pids/thin.pid
address: 127.0.0.1
timeout: 5
port: 5000
log: /home/jd/allods/webapp/current/log/thin.log
max_conns: 1024
require: ['rubygems']

environment: corvus
max_persistent_conns: 512
servers: 1
daemonize: true
chdir: /home/jd/allods/webapp/current
