---
  :all:
    void: &void
    character:
      archetypes:
        - :warrior
        - :paladin
        - :scout
        - :healer
        - :warden
        - :mage
        - :summoner
        - :psionicist

      levels:
        min: 1
        max: 47

      armours:
        cloth: &cloth
          - :cloth
        leather: &leather
          - :leather
        plate: &plate
          - :plate

        list:
          <<: [*cloth, *leather, *plate, *void]

        for:
          warrior:
            <<: [*plate, *void]
          paladin:
            <<: [*plate, *void]
          scout:
            <<: [*leather, *void]
          healer:
            <<: [*plate, *void]
          warden:
            <<: [*leather, *void]
          mage:
            <<: [*cloth, *void]
          summoner:
            <<: [*cloth, *void]
          psionicist:
            <<: [*leather, *void]

      roles:
        tank: &tank_roles
          - :tank
          - :main_tank
          - :off_tank
        healer: &healer_roles
          - :healer
          - :off_healer
        assist: &assist_roles
          - :assist
        control: &control_roles
          - :control
        dps: &dps_roles
          - :dps
          - :off_dps

        for:
          warrior:
            <<: [*tank_roles, *healer_roles, *void]
          paladin:
            <<: [*tank_roles, *healer_roles, *void]
          scout:
            <<: [*dps_roles, *control_roles, *void]
          healer:
            <<: [*healer_roles, *dps_roles, *void]
          warden:
            <<: [*dps_roles, *control_roles, *healer_roles, *assist_roles, *void]
          mage:
            <<: [*dps_roles, *healer_roles, *control_roles, *void]
          summoner:
            <<: [*dps_roles, *control_roles, *healer_roles, *assist_roles, *void]
          psionicist:
            <<: [*control_roles, *assist_roles, *void]

        list:
          <<: [*tank_roles, *healer_roles, *assist_roles, *control_roles, *dps_roles, *void]

      backend:
        list:
          - :energy
          - :mana
        for:
          warrior: :energy
          paladin: :energy
          scout: :energy
          healer: :mana
          warden: :mana
          mage: :mana
          summoner: :mana
          psionicist: :mana

        energy:
          - :warrior
          - :paladin
          - :scout

        mana:
          - :healer
          - :warden
          - :mage
          - :summoner
          - :psinicist
